name: Build Fabric Mod

on:
  push:
    branches: [ "main" ]  # 触发构建的分支
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 拉取代码

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Minecraft 1.20.1 需要 Java 17
          distribution: 'temurin'  # 使用 Adoptium/Temurin JDK

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew  # 确保 gradlew 可执行（Linux/macOS 需要）

      - name: Build with Gradle
        run: ./gradlew build  # 运行构建

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mod-artifact
          path: build/libs/*.jar  # 上传生成的 JAR 文件
